name: credit_cat
version: 0.4.1
description: A library for checking credit cards with the Luhn algorithm.
homepage: https://github.com/amscotti/credit_cat
dev_dependencies: 
  test: ^1.20.1
environment:
  sdk: '>=2.14.0 <3.0.0' 